data_ingestion:
  test_size: 0.25
  raw_file: raw/data.csv

feature_engineering:
  max_features: 50
  vectorizer_name: "vectorizer_name"

model_training:
  random_state: 42
  model_name: "capstone_model"
